name: build

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install apt packages
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq build-essential gpg

    - name: build
      run: ./build.sh linux x86_64 && mv -v releases/bash bash-linux-x86_64
      shell: bash

    - uses: actions/upload-artifact@v3  
      with:
        name: bash-linux-x86_64
        path: bash-linux-x86_64

    - name: Compute Short SHA
      id: ssha
      run: |
        echo "ssha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    outputs:
      ssha: ${{ steps.ssha.outputs.ssha }}


  release:
    permissions: write-all
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: bash-linux-x86_64

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Continuous ${{ needs.build.outputs.ssha }}
          automatic_release_tag: ${{ needs.build.outputs.ssha }}
          prerelease: false
          draft: false
          files: |
            ./bash-linux-x86_64
          repo_token: ${{ secrets.GITHUB_TOKEN }}
