name: build

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install apt packages
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq build-essential gpg

    - name: build
      run: |
        for arch in x86_64 aarch64; do
          ./build.sh linux "${arch}" && mv -v releases/bash "bash-linux-${arch}"
        done
      shell: bash

    - uses: actions/upload-artifact@v3  
      with:
        name: bash-linux
        path: bash-linux-*

    - name: Compute Short SHA
      id: ssha
      run: |
        echo "ssha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    outputs:
      ssha: ${{ steps.ssha.outputs.ssha }}


  release:
    permissions: write-all
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: bash-linux

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Continuous ${{ needs.build.outputs.ssha }}
          automatic_release_tag: ${{ needs.build.outputs.ssha }}
          prerelease: false
          draft: false
          files: |
            ./bash-linux
          repo_token: ${{ secrets.GITHUB_TOKEN }}
